name: Create Tag/Release

on:
  push:
    branches:
      - main

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_branches: stable
          tag_prefix:
      - name: Generate CHANGELOG
        env:
          CHANGELOG_GITHUB_TOKEN: ${{ secrets.SECRET_GITHUB_TOKEN }}
        run: |
          gem install github_changelog_generator
          github_changelog_generator -u archanaserver -p action-workflow
      - name: Commit files
        run: |
          git config --local user.email "$GITHUB_EMAIL"
          git config --local user.name "$GITHUB_USERNAME"
          git commit -m "doc(CHANGELOG): update" -a
        env:
          GITHUB_USERNAME: archanaserver
          GITHUB_EMAIL: ak3196046@gmail.com
      - name: Push changes from
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.SECRET_GITHUB_TOKEN }}
          branch: ${{ github.ref }}
      - name: Push changes to
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          repository: archanaserver/action-workflow-push
