name: Automatic pull request

on:
  push:
    branches:
    - "master"  # Support wildcard matching

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: pull-request
      uses: repo-sync/pull-request@v2
      with:
        source_branch: ""
        destination_branch: "pre-prod"
        pr_title: "Pulling ${{ github.ref }} into master"
        pr_body: ":crown: *An automated PR*"
        pr_draft: true
        pr_allow_empty: true
        github_token: ${{ secrets.SECRET_GITHUB_ACCESS_TOKEN }}
